package com.ytmj.jzgl.domain;

import java.util.Date;

public class Announcement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.id
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.title
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.content
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.image
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.time
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.id
     *
     * @return the value of announcement.id
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.id
     *
     * @param id the value for announcement.id
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.title
     *
     * @return the value of announcement.title
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.title
     *
     * @param title the value for announcement.title
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.content
     *
     * @return the value of announcement.content
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.content
     *
     * @param content the value for announcement.content
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.image
     *
     * @return the value of announcement.image
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.image
     *
     * @param image the value for announcement.image
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.time
     *
     * @return the value of announcement.time
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.time
     *
     * @param time the value for announcement.time
     *
     * @mbg.generated Tue Apr 14 13:29:43 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}