package com.ytmj.jzgl.domain;

public class Drug {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.name
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.count
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    private String count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.money
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    private String money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.id
     *
     * @return the value of drug.id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.id
     *
     * @param id the value for drug.id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.name
     *
     * @return the value of drug.name
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.name
     *
     * @param name the value for drug.name
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money;
    }
}