package com.ytmj.jzgl.domain;

public class ICheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.id
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.name
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.description
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.id
     *
     * @return the value of check.id
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.id
     *
     * @param id the value for check.id
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.name
     *
     * @return the value of check.name
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.name
     *
     * @param name the value for check.name
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.description
     *
     * @return the value of check.description
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.description
     *
     * @param description the value for check.description
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}