package com.ytmj.jzgl.domain;

public class Imgs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.id
     *
     * @mbg.generated Tue Apr 14 11:37:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.name
     *
     * @mbg.generated Tue Apr 14 11:37:29 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.url
     *
     * @mbg.generated Tue Apr 14 11:37:29 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.id
     *
     * @return the value of imgs.id
     *
     * @mbg.generated Tue Apr 14 11:37:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.id
     *
     * @param id the value for imgs.id
     *
     * @mbg.generated Tue Apr 14 11:37:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.name
     *
     * @return the value of imgs.name
     *
     * @mbg.generated Tue Apr 14 11:37:29 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.name
     *
     * @param name the value for imgs.name
     *
     * @mbg.generated Tue Apr 14 11:37:29 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.url
     *
     * @return the value of imgs.url
     *
     * @mbg.generated Tue Apr 14 11:37:29 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.url
     *
     * @param url the value for imgs.url
     *
     * @mbg.generated Tue Apr 14 11:37:29 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}