package com.ytmj.jzgl.domain;

import java.util.Date;

public class MedicalRecord {
    private String state;

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicalrecord.id
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicalrecord.visittime
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    private String  visittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicalrecord.conclusion
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    private String conclusion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicalrecord.symptom
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    private String symptom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicalrecord.drug
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    private String drug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicalrecord.doctor
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    private String doctor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicalrecord.drugnum
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    private String drugnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicalrecord.id
     *
     * @return the value of medicalrecord.id
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicalrecord.id
     *
     * @param id the value for medicalrecord.id
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public String getVisittime() {
        return visittime;
    }

    public void setVisittime(String visittime) {
        this.visittime = visittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicalrecord.conclusion
     *
     * @return the value of medicalrecord.conclusion
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public String getConclusion() {
        return conclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicalrecord.conclusion
     *
     * @param conclusion the value for medicalrecord.conclusion
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public void setConclusion(String conclusion) {
        this.conclusion = conclusion == null ? null : conclusion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicalrecord.symptom
     *
     * @return the value of medicalrecord.symptom
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicalrecord.symptom
     *
     * @param symptom the value for medicalrecord.symptom
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicalrecord.drug
     *
     * @return the value of medicalrecord.drug
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public String getDrug() {
        return drug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicalrecord.drug
     *
     * @param drug the value for medicalrecord.drug
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public void setDrug(String drug) {
        this.drug = drug == null ? null : drug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicalrecord.doctor
     *
     * @return the value of medicalrecord.doctor
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public String getDoctor() {
        return doctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicalrecord.doctor
     *
     * @param doctor the value for medicalrecord.doctor
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public void setDoctor(String doctor) {
        this.doctor = doctor == null ? null : doctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicalrecord.drugnum
     *
     * @return the value of medicalrecord.drugnum
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public String getDrugnum() {
        return drugnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicalrecord.drugnum
     *
     * @param drugnum the value for medicalrecord.drugnum
     *
     * @mbg.generated Sat Apr 18 16:49:20 CST 2020
     */
    public void setDrugnum(String drugnum) {
        this.drugnum = drugnum == null ? null : drugnum.trim();
    }
}