package com.ytmj.jzgl.domain;

public class PatientMid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_med.id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_med.patient_id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    private Integer patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_med.medicalrecord_id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    private Integer medicalrecordId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_med.id
     *
     * @return the value of patient_med.id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_med.id
     *
     * @param id the value for patient_med.id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_med.patient_id
     *
     * @return the value of patient_med.patient_id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_med.patient_id
     *
     * @param patientId the value for patient_med.patient_id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_med.medicalrecord_id
     *
     * @return the value of patient_med.medicalrecord_id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public Integer getMedicalrecordId() {
        return medicalrecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_med.medicalrecord_id
     *
     * @param medicalrecordId the value for patient_med.medicalrecord_id
     *
     * @mbg.generated Sat Apr 18 15:26:40 CST 2020
     */
    public void setMedicalrecordId(Integer medicalrecordId) {
        this.medicalrecordId = medicalrecordId;
    }
}