package com.ytmj.jzgl.domain;

import java.util.Date;
import java.util.List;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.id
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private Integer id;
    private String sfcz;

    public String getSfcz() {
        return sfcz;
    }

    public void setSfcz(String sfcz) {
        this.sfcz = sfcz;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.name
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.age
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.sex
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.number
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.money
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.idcard
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.department
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private String  department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.create_time
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private String  create_time;

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.status
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.id
     *
     * @return the value of patient.id
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.id
     *
     * @param id the value for patient.id
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.name
     *
     * @return the value of patient.name
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.name
     *
     * @param name the value for patient.name
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.age
     *
     * @return the value of patient.age
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.age
     *
     * @param age the value for patient.age
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.sex
     *
     * @return the value of patient.sex
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.sex
     *
     * @param sex the value for patient.sex
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.number
     *
     * @return the value of patient.number
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.number
     *
     * @param number the value for patient.number
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.money
     *
     * @return the value of patient.money
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.money
     *
     * @param money the value for patient.money
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.idcard
     *
     * @return the value of patient.idcard
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.idcard
     *
     * @param idcard the value for patient.idcard
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.status
     *
     * @return the value of patient.status
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public String getStatus() {
        return status;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.status
     *
     * @param status the value for patient.status
     *
     * @mbg.generated Wed Apr 15 00:48:15 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
    private List<MedicalRecord> list;

    public List<MedicalRecord> getList() {
        return list;
    }

    public void setList(List<MedicalRecord> list) {
        this.list = list;
    }


}