package com.ytmj.jzgl.domain;

public class PCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pcheck.id
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pcheck.pname
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pcheck.name
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pcheck.id
     *
     * @return the value of pcheck.id
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pcheck.id
     *
     * @param id the value for pcheck.id
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pcheck.pname
     *
     * @return the value of pcheck.pname
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pcheck.pname
     *
     * @param pname the value for pcheck.pname
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pcheck.name
     *
     * @return the value of pcheck.name
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pcheck.name
     *
     * @param name the value for pcheck.name
     *
     * @mbg.generated Sat Apr 18 21:34:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}