package com.ytmj.jzgl.domain;

public class RoleUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.id
     *
     * @mbg.generated Mon Apr 06 20:53:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.role_id
     *
     * @mbg.generated Mon Apr 06 20:53:17 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.user_id
     *
     * @mbg.generated Mon Apr 06 20:53:17 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.id
     *
     * @return the value of role_user.id
     *
     * @mbg.generated Mon Apr 06 20:53:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.id
     *
     * @param id the value for role_user.id
     *
     * @mbg.generated Mon Apr 06 20:53:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.role_id
     *
     * @return the value of role_user.role_id
     *
     * @mbg.generated Mon Apr 06 20:53:17 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.role_id
     *
     * @param roleId the value for role_user.role_id
     *
     * @mbg.generated Mon Apr 06 20:53:17 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.user_id
     *
     * @return the value of role_user.user_id
     *
     * @mbg.generated Mon Apr 06 20:53:17 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.user_id
     *
     * @param userId the value for role_user.user_id
     *
     * @mbg.generated Mon Apr 06 20:53:17 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}