package com.ytmj.jzgl.domain;

public class Viewdepartment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viewdepartment.id
     *
     * @mbg.generated Wed Apr 15 01:06:09 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viewdepartment.name
     *
     * @mbg.generated Wed Apr 15 01:06:09 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viewdepartment.description
     *
     * @mbg.generated Wed Apr 15 01:06:09 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viewdepartment.id
     *
     * @return the value of viewdepartment.id
     *
     * @mbg.generated Wed Apr 15 01:06:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viewdepartment.id
     *
     * @param id the value for viewdepartment.id
     *
     * @mbg.generated Wed Apr 15 01:06:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viewdepartment.name
     *
     * @return the value of viewdepartment.name
     *
     * @mbg.generated Wed Apr 15 01:06:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viewdepartment.name
     *
     * @param name the value for viewdepartment.name
     *
     * @mbg.generated Wed Apr 15 01:06:09 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viewdepartment.description
     *
     * @return the value of viewdepartment.description
     *
     * @mbg.generated Wed Apr 15 01:06:09 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viewdepartment.description
     *
     * @param description the value for viewdepartment.description
     *
     * @mbg.generated Wed Apr 15 01:06:09 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}